#!/bin/bash

OPTS="-n username:password"
DIR1="/path/to/downloads"
DIR2="/path/to/incomplete"
AGENT="$1" # napiprojekt.py or ss-retry

function cli() {
    transmission-remote $OPTS "$@"
}

function list_torrents() {
    cli -l | awk '{print $1}'
}

function list_complete_files() {
    cli -t "$1" -if | tail -n +3 | grep 100% | sed 's/^.*\?[0-9] .B \+//'
}

for id in `list_torrents`; do
    list_complete_files "$id" | grep -iE '\.mp4|\.avi|\.mkv|\.mov|\.wmv|\.mpg|\.flv' | while read file; do
        [ -f "$DIR1/$file" ] && "$AGENT" "$DIR1/$file"
        [ -f "$DIR2/$file" ] && "$AGENT" "$DIR2/$file"
	done
done
